export const FETCH_AUTOFILL_FIELDS = 'FETCH_AUTOFILL_FIELDS';
export const FETCH_AUTOFILL_FIELDS_SUCCESS = 'FETCH_AUTOFILL_FIELDS_SUCCESS';
export const FETCH_AUTOFILL_FIELDS_ERROR = 'FETCH_AUTOFILL_FIELDS_ERROR';
