export const FETCH_AUTOFILL_FIELDS = 'FETCH_AUTOFILL_FIELDS';
export const FETCH_AUTOFILL_FIELDS_SUCCESS = 'FETCH_AUTOFILL_FIELDS_SUCCESS';
export const FETCH_AUTOFILL_FIELDS_ERROR = 'FETCH_AUTOFILL_FIELDS_ERROR';

export const SAVE_QUERY = 'SAVE_QUERY';
export const SAVE_QUERY_SUCCESS = 'SAVE_QUERY_SUCCESS';
export const SAVE_QUERY_ERROR = 'SAVE_QUERY_ERROR';
